# Generated by Django 4.2.10 on 2024-04-09 00:35

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
    ]
