# Generated by Django 4.2.10 on 2024-04-08 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passaccess",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pass_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="study.course",
            ),
        ),
        migrations.AddField(
            model_name="groupstudents",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="study.group"
            ),
        ),
        migrations.AddField(
            model_name="groupstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="study.course",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="student",
            field=models.ManyToManyField(
                through="study.GroupStudents", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор курса",
            ),
        ),
        migrations.AddConstraint(
            model_name="passaccess",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstudents",
            constraint=models.UniqueConstraint(
                fields=("student", "group"), name="unique_student_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("author", "name"), name="unique_author_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("min_group_people__lte", models.F("max_group_people"))),
                name="Минимальное количество участников не должно быть больше максимального",
            ),
        ),
    ]
