# Generated by Django 4.2.10 on 2024-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.URLField(
                help_text="Укажите ссылку на видео",
                max_length=150,
                unique=True,
                verbose_name="Cсылка на видео урок",
            ),
        ),
    ]
