# Generated by Django 4.2.10 on 2024-02-29 01:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study", "0003_alter_lesson_link_to_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="pass",
            options={"verbose_name_plural": "Pass"},
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                help_text="Укажите название группы",
                max_length=150,
                verbose_name="Название группы",
            ),
        ),
        migrations.RemoveField(
            model_name="group",
            name="student",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="study.educationcourse",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                help_text="Укажите название урока",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[а-яА-ЯёЁa-zA-Z]*$",
                        "Поле должно содержать только буквы кириллицы/латиницы",
                    )
                ],
                verbose_name="Название урока",
            ),
        ),
        migrations.AddConstraint(
            model_name="pass",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
        migrations.AddField(
            model_name="groupstudents",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="study.group"
            ),
        ),
        migrations.AddField(
            model_name="groupstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="student",
            field=models.ManyToManyField(
                through="study.GroupStudents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
